# Generated by Django 5.0 on 2025-03-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='最后题目修改时间'),
        ),
        migrations.AddField(
            model_name='submission',
            name='last_assignment_modified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='提交时作业版本'),
        ),
    ]
